### PR TITLE
Fix cut with duplicate breaks

### LINKED ISSUE #244: cut produces duplicate levels
See:
```
julia> levels(cut([zeros(1000); ones(1000)], 10))
8-element Array{String,1}:
 "[0.0, 0.0)"
 "[0.0, 0.0)"
 "[0.0, 0.0)"
 "[0.0, 0.5)"
 "[0.5, 1.0)"
 "[1.0, 1.0)"
 "[1.0, 1.0)"
 "[1.0, 1.0]"

julia> unique(levels(cut([zeros(1000); ones(1000)], 10)))
5-element Array{String,1}:
 "[0.0, 0.0)"
 "[0.0, 0.5)"
 "[0.5, 1.0)"
 "[1.0, 1.0)"
 "[1.0, 1.0]"
```

@nalimilan - I feel this is a serious problem with cut.

### PR DESCRIPTION
**Pull request by nalimilan**
We could allow passing duplicate labels and have them be merged into a single level, but that's for later.

Fixes #244.

### CODE REVIEW

**Comment by bkamins** [comment]
Thank you. Can you please also fix the typo in the docsting in line https://github.com/JuliaData/CategoricalArrays.jl/pull/245/files#diff-0e27ad0a2d2d952a6b4e82aa6cf9a5daL67 (there is a missing ` on that line)

File: src/extras.jl [hunk 1]
```diff
@@ -113,6 +113,10 @@ function cut(x::AbstractArray{T, N}, breaks::AbstractVector;
              extend::Bool=false,
              labels::Union{AbstractVector{<:AbstractString},Function}=default_formatter,
              allow_missing::Bool=false) where {T, N}
+    if !allunique(breaks)
+        throw(ArgumentError("all breaks must be unique"))
```
Comment (bkamins) [inline src/extras.jl]: I think it is OK to just throw an error. I would just highlight the user to pass custom labels as a vector or as a function so that the user knows how to fix the problem. Then it might be good to export `default_formatter` (with some better name) so that then the user can reuse it for users own formatting. The reason is that when I asked people how they would resolve it is to prepend the bin number before the range eg something like "1: [1,2]"` or similar, so it would be nice to be able to reuse a default formatter. Also then probably it would be better to pass data into a formatter as a named tuple as it is easier to handle using anonymous functions, because you could write something like:
```
x - > string(x.i) * ": " * default_formatter(x)
```
(those are just loose thoughts - the key point is to prompt user how to solve the problem not only that there is a problem)

The key issue is that often reducing a number of bins is not an option as you want to eg. have high granularity on the tail of the distribution even if it is concentrated in the center of the mass.

Comment (nalimilan) [reply src/extras.jl]: Mmm, your reply seems to indicate that we should support this with a simpler solution. Exporting the default formatter would be useful anyway, but that's relatively complex to use. And that doesn't avoid the error about duplicate breaks.

So maybe we should add an argument to allow duplicate breaks as long as they have distinct labels. When a number of quantiles is specified rather than explicit breaks, maybe the formatter should print the quantile number by default, and allow duplicate breaks?

Comment (bkamins) [reply src/extras.jl]: > When a number of quantiles is specified rather than explicit breaks, maybe the formatter should print the quantile number by default, and allow duplicate breaks?

This was my initial thought, but I did not want to add work for you with this (as this can be achieved with a custom formatter). The only problem with this is that the string `cut` produces are usually used in plots as x-axis, when quantile number is not needed. So maybe we can add a kwarg if a quantile number should be added or not by default_formatter as a half measure (that would be `false` by default and the error message could indicate that if `default_formatter` is used then it can be set to `true` to avoid the problem)

Comment (nalimilan) [reply src/extras.jl]: Actually I was thinking the quantile number is an interesting information when you requested quantiles (rather than specific break points). Sometimes you don't even want to see the actual values. What do you think?

Comment (bkamins) [reply src/extras.jl]: I think that it is useful, but it would be good to be able to opt-out. As noted - if you do a histogram you typically want x-axis just to give the ranges on the plot.

Comment (nalimilan) [reply src/extras.jl]: Yes, of course. Maybe we can just provide two formatters, keeping the current one when you pass a vector of breaks, but using another one when you pass a number of quantiles?

Comment (bkamins) [reply src/extras.jl]: Before we move forward with this discussion - it seems that actually it seems we have even a more different situation:
```
julia> Random.seed!(1234); z = shuffle!([zeros(10); ones(10)])
20-element Array{Float64,1}:
 0.0
 0.0
 1.0
 1.0
 0.0
 0.0
 0.0
 1.0
 0.0
 1.0
 1.0
 0.0
 1.0
 1.0
 0.0
 0.0
 1.0
 0.0
 1.0
 1.0

julia> zc = cut(z, 10)
20-element CategoricalArray{String,1,UInt32}:
 "[0.0, 0.5)"
 "[0.0, 0.5)"
 "[1.0, 1.0]"
 "[1.0, 1.0]"
 "[0.0, 0.5)"
 "[0.0, 0.5)"
 "[0.0, 0.5)"
 "[1.0, 1.0]"
 "[0.0, 0.5)"
 "[1.0, 1.0]"
 "[1.0, 1.0]"
 "[0.0, 0.5)"
 "[1.0, 1.0]"
 "[1.0, 1.0]"
 "[0.0, 0.5)"
 "[0.0, 0.5)"
 "[1.0, 1.0]"
 "[0.0, 0.5)"
 "[1.0, 1.0]"
 "[1.0, 1.0]"

julia> zc.refs
20-element Array{UInt32,1}:
 0x00000004
 0x00000004
 0x00000008
 0x00000008
 0x00000004
 0x00000004
 0x00000004
 0x00000008
 0x00000004
 0x00000008
 0x00000008
 0x00000004
 0x00000008
 0x00000008
 0x00000004
 0x00000004
 0x00000008
 0x00000004
 0x00000008
 0x00000008

julia> levels(zc)
8-element Array{String,1}:
 "[0.0, 0.0)"
 "[0.0, 0.0)"
 "[0.0, 0.0)"
 "[0.0, 0.5)"
 "[0.5, 1.0)"
 "[1.0, 1.0)"
 "[1.0, 1.0)"
 "[1.0, 1.0]"

julia> droplevels!(zc); levels(zc)
2-element Array{String,1}:
 "[0.0, 0.5)"
 "[1.0, 1.0]"
```

So - maybe it is enough to ensure we `droplevels!` after cutting? You know the sources better so maybe you can quickly validate this assumption? But it seems to me that we actually do not use those "extra duplicate" levels the code produces.

**Comment by nalimilan** [comment]
I've pushed a possible solution: add an `allowempty` keyword argument. It's `false` by default, meaning duplicate breaks are not allowed. I think that's good as it forces people to think about what they want to do. If it's `true`, duplicates are allowed:
- For `cut(x, ngroups)`, we use `"Q$i: [$from, $to)` as the default format, so that quantiles are always unique. Quantiles with duplicate breaks are empty, but exist as unused levels.
- For `cut(x, breaks)`, empty intervals are added as `($from, $to)` levels. With the default formatter, if a break appears more than twice, duplicate labels are generated, which triggers an error. I considered dropping empty intervals with duplicate names, but that requires recoding references and it's an uncommon case anyway so probably not worth doing.

This is open to discussion. A few things to highlight:
-  `($from, $to)` was  `[$from, $to)` before I made some adjustments. Even if according to mathematical notation both mean the same thing when `$from == $to`, I think the former is clearer. Actually I wasn't aware they are equivalent. Intuitively, I would have thought `[$x, $x)` is equivalent to `[$x, $x]`, and I thought we would have to include `x` in that interval instead of having it be empty. But that would require adjusting the next interval to be left-open; the advantage of the proposed approach is that intervals that are not empty are not affected by the presence of empty intervals, so `droplevels(cut(x, breaks, allowempty=true))` gives the same result as `cut(x, unique(breaks))`.
- `"Q$i: [$from, $to)` is a bit verbose, but if you asked for quantiles it probably makes sense as a default.
- The fact that `cut(x, breaks, allowempty=false)` throws an error when a break appears more than twice makes it quite useless in practice with the default formatter. But we can't really change that as it wouldn't be very useful to print `$i` for the default formatter in that case. I think `allowempty` is only useful with `cut(x, breaks)` if you want to compute quantiles based on breaks computed beforehand (e.g. common to several samples). In that case, you will have to provide labels manually; at some point we could export formatters, or add convenience arguments.

File: src/extras.jl [hunk 2]
```diff
@@ -60,17 +61,21 @@ i.e. the lower bound is included and the upper bound is excluded.
...
 * `labels::Union{AbstractVector,Function}: a vector of strings giving the names to use for
-  the intervals; or a function `f(from, to, i; closed)` that generates the labels from the
-  left and right interval boundaries and the group index. Defaults to 
+  the intervals; or a function `f(from, to, i; leftclosed, rightclosed)` that generates
+  the labels from the left and right interval boundaries and the group index. Defaults to
   `"[from, to)"` (or `"[from, to]"` for the rightmost interval if `extend == true`).
 * `allow_missing::Bool=true`: when `true`, values outside of breaks result in missing values.
   only supported when `x` accepts missing values.
-  
+* `allowempty::Bool=false`: when `false`, an error is raised if some breaks appear
```
Comment (bkamins) [inline src/extras.jl:74]: This is OK. Probably `allowempty=true` here is not very intuitive, but sometimes breaks might be generated programmatically so it is OK to have this.

File: src/extras.jl [hunk 3]
```diff
@@ -142,36 +152,70 @@ function cut(x::AbstractArray{T, N}, breaks::AbstractVector;
...
     n = length(breaks)
     if labels isa Function
-        @static if VERSION >= v"0.7.0-DEV.4524"
-            from = map(x -> sprint(show, x, context=:compact=>true), breaks[1:n-1])
-            to = map(x -> sprint(show, x, context=:compact=>true), breaks[2:n])
-        else
-            from = map(x -> sprint(showcompact, x), breaks[1:n-1])
-            to = map(x -> sprint(showcompact, x), breaks[2:n])
-        end
+        from = map(x -> sprint(show, x, context=:compact=>true), breaks[1:n-1])
```
Comment (bkamins) [inline src/extras.jl:155]: why do we pass strings not values to `levels` function?

Comment (nalimilan) [reply src/extras.jl:155]: Woops. Will change that in another PR.

File: src/extras.jl [hunk 4]
```diff
@@ -142,36 +152,70 @@ function cut(x::AbstractArray{T, N}, breaks::AbstractVector;
...
+        levs[end] = labels(from[end], to[end], n-1,
+                           leftclosed=breaks[end-1] != breaks[end], rightclosed=extend)
     else
         length(labels) == n-1 || throw(ArgumentError("labels must be of length $(n-1), but got length $(length(labels))"))
         # Levels must have element type String for type stability of the result
         levs::Vector{String} = copy(labels)
     end
+    if !allunique(levs)
+        if labels === default_formatter
+            throw(ArgumentError("all labels must be unique, but `breaks` contains duplicates: " *
```
Comment (bkamins) [inline src/extras.jl:171]: this might also happen if `sprint` produces duplicates for different values. maybe in https://github.com/JuliaData/CategoricalArrays.jl/pull/245/files#diff-0e27ad0a2d2d952a6b4e82aa6cf9a5daR160 and https://github.com/JuliaData/CategoricalArrays.jl/pull/245/files#diff-0e27ad0a2d2d952a6b4e82aa6cf9a5daR163 we should compare `from` and `to` instead.

See e.g.:
```
julia> sprint(show, 1.000001, context=:compact=>true)
"1.0"

julia> sprint(show, 1.000002, context=:compact=>true)
"1.0"

julia> sprint(show, 1.000003, context=:compact=>true)
"1.0"
```

File: src/extras.jl [hunk 5]
```diff
@@ -142,36 +152,70 @@ function cut(x::AbstractArray{T, N}, breaks::AbstractVector;
...
 
 Cut a numeric array into `ngroups` quantiles, determined using
 [`quantile`](@ref).
+
+# Keyword arguments
+* `labels::Union{AbstractVector,Function}: a vector of strings giving the names to use for
+  the intervals; or a function `f(from, to, i; leftclosed, rightclosed)` that generates
+  the labels from the left and right interval boundaries and the group index. Defaults to
+  `"Qi: [from, to)"` (or `"Qi: [from, to]"` for the rightmost interval if `extend == true`).
+* `allowempty::Bool=false`: when `false`, an error is raised if some breaks appear
```
Comment (bkamins) [inline src/extras.jl:204]: I would be more explicit here saying that when some quantiles are equal.

File: src/extras.jl [hunk 6]
```diff
@@ -142,36 +152,70 @@ function cut(x::AbstractArray{T, N}, breaks::AbstractVector;
...
+  multiple times, generating empty intervals; when `true`, duplicate breaks are allowed
+  and the intervals they generate are kept as unused levels
+  (but duplicate labels are not allowed).
 """
-cut(x::AbstractArray, ngroups::Integer;
-    labels::Union{AbstractVector{<:AbstractString},Function}=default_formatter) =
-    cut(x, Statistics.quantile(x, (1:ngroups-1)/ngroups); extend=true, labels=labels)
+function cut(x::AbstractArray, ngroups::Integer;
+             labels::Union{AbstractVector{<:AbstractString},Function}=default_formatter,
```
Comment (bkamins) [inline src/extras.jl:210]: why it is `default_formatter` here and above you defined `quantile_formatter`?

File: src/extras.jl (hunk 4 above)
Comment (nalimilan) [reply src/extras.jl:171]: Good catch. But even in that case we should not allow duplicate labels. The solution would be to generate new labels with a higher precision. I'd say we can leave this for later as it won't break anything and it's mostly orthogonal to this PR.

File: src/extras.jl (hunk 6 above)
Comment (nalimilan) [reply src/extras.jl:210]: That's a typo.

**Comment by bkamins** [comment]
I think what you proposed is OK (at least it is safe as a default for now). Errors print the information what to do when `allowempty=false` so it is easy to fix.

I have left some minor comments (mainly the differences between `breaks` and `from` and `to` in corner cases when `sprint` has the same output for different inputs)
