### PR TITLE
Fix sort with unused levels

### LINKED ISSUE #269: Unexpected behaviour using sort
```julia
julia> v= categorical(collect("dcba"))[1:3]
3-element CategoricalArray{Char,1,UInt32}:
 'd'
 'c'
 'b'

julia> sort(v)
3-element CategoricalArray{Char,1,UInt32}:
 'a'
 'b'
 'c'

julia> Pkg.installed()["CategoricalArrays"]
v"0.8.0"
```

### PR DESCRIPTION
**Pull request by nalimilan**
The code did not handle correctly the case when unused levels were present at the front.
This seems to have become easier to trigger since the index vs. levels distinction was dropped.

Fixes #269.

### CODE REVIEW

File: src/array.jl [hunk 1]
```diff
@@ -943,16 +943,17 @@ function Base.sort!(v::CategoricalVector;
 
     # compute the order in which to read from counts
     ord = Base.Sort.ord(lt, by, rev, order)
-    index = eltype(v) >: Missing ? [missing; v.pool.valindex] : v.pool.valindex
     seen = counts .> 0
     anymissing = eltype(v) >: Missing && seen[1]
-    perm = sortperm(view(index, seen), order=ord)
-    nzcounts = counts[seen]
+    levs = eltype(v) >: Missing ? [missing; v.pool.valindex] : v.pool.valindex
+    sortedlevs = sort(Vector(view(levs, seen)), order=ord)
```
Comment (bkamins) [inline src/array.jl:949]: why not use? `sort!(levs[seen], order=ord)`

File: src/array.jl [hunk 2]
```diff
@@ -943,16 +943,17 @@ function Base.sort!(v::CategoricalVector;
...
+    levelsmap = something.(indexin(sortedlevs, levs))
```
Comment (bkamins) [inline src/array.jl:950]: why is this `something.` needed?

File: src/array.jl (hunk 1 above)
Comment (nalimilan) [reply src/array.jl:949]: We need a `Vector` to avoid calling ourselves and getting a stack overflow. But yes `sort!` should work.

File: src/array.jl (hunk 2 above)
Comment (nalimilan) [reply src/array.jl:950]: That gets rid of the `Union{Nothing, Int}` eltype, so it should be better for performance in the loop, and it also ensures we get an error if something unexpected happens.

File: src/array.jl (hunk 1 above)
Comment (bkamins) [reply src/array.jl]: `levs[seen]` would create a new vector anyway - right? But this is minor I guess so it can stay as is.

File: src/array.jl (hunk 2 above)
Comment (bkamins) [reply src/array.jl:950]: Ah - I thought `indexin` does the narrowest possible type - indeed it always produces `Union{Nothing, Int}` so this is needed.

File: src/array.jl (hunk 1 above)
Comment (nalimilan) [reply src/array.jl]: Actually there's a weird behavior which creates a `CategoricalVector` with logical indexing. Need to investigate that...

Comment (nalimilan) [reply src/array.jl]: This is so tricky that I ended up filing a design issue against Base: https://github.com/JuliaLang/julia/issues/36106.
